### ISSUE TITLE
TypeError: o.Mediator is undefined

### ISSUE THREAD

**Issue by etlweather** [lucasrodcosta/clappr-nerd-stats#26]
Nerd Stats: Version 2.0.2
Clappr 0.4.7

This error comes up at page load time.

**Comment by lucasrodcosta** [comment]
Hi @etlweather.

I couldn't reproduce the error.
Could you please provide more info?
It would also help a lot if you could share a code snippet so I can reproduce and debug it here too.

Thank you so much.
