### ISSUE TITLE
Atualizar plugin para versões novas do Clappr

### ISSUE THREAD

**Issue by juliovedovatto** [lucasrodcosta/clappr-nerd-stats#5]
Estamos fazendo um bundle com o Clappr, instalando via `npm`. Ao instalar o plugin, notei que o pacote está desatualizado com o formato novo que foi tomado com o Clappr.

* `clappr-stats` não está listado nas `dependencies` no `package.json`. O Clappr está.
* Aparentemente agora o `clappr-stats` (https://github.com/clappr/clappr-stats) é `@clappr/stats-plugin` agora e pede o `@clappr/core` como dependência.
* Pra este pacote, precisa também atualizar a dependencia do `clappr` para `@clappr/core`

Do jeito que está, me retorna esse erro no bundler (rollup):

```
 Bundling Warning UNRESOLVED_IMPORT
           'ClapprStats' is imported by node_modules/clappr-nerd-stats/dist/clappr-nerd-stats.js, but could not be
           resolved – treating it as an external dependency
```

Como uso esse bundle em outro lugar, não consigo fazer a build.

É possível atualizar esse plugin p/ formato novo ou ele foi descontinuado @lucasrodcosta?

**Comment by lucasrodcosta** [comment]
Oi @juliovedovatto! Muito obrigado por reportar essa issue!

O projeto não está descontinuado não. Posso atualizar ele aqui sim.

Mas antes, você já fez algum fork aí pra corrigir o problema?
Se tiver feito algo, pode submeter um PR que eu faço o merge aqui :)

**Comment by lucasrodcosta** [comment]
Oi @juliovedovatto.
Acabei de fazer um novo release atualizando as dependências.
Você pode testá-la, por favor?

**Comment by lucasrodcosta** [comment]
Fechando a issue por falta de feedback.
